# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'IoTMobileStarter' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for IoTMobileStarter
  pod 'IMFCore'
  pod 'IMFFacebookAuthentication'
  pod 'IMFURLProtocol'

  target 'IoTMobileStarterTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'IMFCore'
    pod 'IMFFacebookAuthentication'
    pod 'IMFURLProtocol'
  end

end

target 'IoTMobileStarterDev' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for IoTMobileStarterDev
  pod 'IMFCore'
  pod 'IMFFacebookAuthentication'
  pod 'IMFURLProtocol'
end
